apiVersion: batch/v1
kind: Job
metadata:
  name: {{ job.name }}
  namespace: {{ job.namespace }}
  labels:
    kueue.x-k8s.io/queue-name: {{ job.queue }}

  {% if job.metadata is defined %}
  annotations:
    interlink.eu/original-metadata: '{{ job.metadata | tojson }}'
  {% endif %}

spec:
  parallelism: 1
  completions: 1
  backoffLimit: 0
  suspend: true
  template:
    spec:
      restartPolicy: Never
      {% if job.spec.initContainers %}
      initContainers:
        {% for container in job.spec.initContainers %}
        - name: {{ container.name }}
          image: {{ container.image }}
          tag: {{ container.tag }}
          command: {{ container.command | tojson }}

          {% if container.args is defined %}
          args: {{ container.args | tojson }}
          {% endif %}

          {% if container.securityContext is defined %}
          securityContext: {{ container.securityContext | tojson }}
          {% endif %}

          {% if container.resources is defined %}
          resources: {{ container.resources | tojson }}
          {% endif %}

          {% if container.env is defined %}
          env: {{ container.env | tojson }}
          {% endif %}

          {% if 'volumeMounts' in container and container.volumeMounts %}
          volumeMounts:
            {% for volumeMount in container.volumeMounts %}
            - name: {{ volumeMount.name }}
              mountPath: {{ volumeMount.mountPath }}

              {% if volumeMount.subPath %}
              subPath: {{ volumeMount.subPath }}
              {% endif %}

              {% if volumeMount.readOnly %}
              readOnly: {{ volumeMount.readOnly }}
              {% endif %}

              {% if volumeMount.readOnly %}
              mountPropagation: {{ volumeMount.mountPropagation }}
              {% endif %}

            {% endfor %}
          {% endif %}
        {% endfor %}
        {% endif %}

      containers:
        {% for container in job.spec.containers %}
        - name: {{ container.name }}
          image: {{ container.image }}
          tag: {{ container.tag }}
          command: {{ container.command | tojson }}

          {% if container.securityContext is defined %}
          securityContext: {{ container.securityContext | tojson }}
          {% endif %}

          {% if container.args is defined %}
          args: {{ container.args | tojson }}
          {% endif %}

          {% if container.resources is defined %}
          resources: {{ container.resources | tojson }}
          {% endif %}

          {% if container.env is defined %}
          env: {{ container.env | tojson }}
          {% endif %}

          {% if 'volumeMounts' in container and container.volumeMounts %}
          volumeMounts:
            {% for volumeMount in container.volumeMounts %}
            - name: {{ volumeMount.name }}
              mountPath: {{ volumeMount.mountPath }}

              {% if volumeMount.subPath %}
              subPath: {{ volumeMount.subPath }}
              {% endif %}

            {% endfor %}
          {% endif %}
        {% endfor %}

      {% if job.spec.volumes is defined %}
      volumes:
        {% for volume in job.spec.volumes %}
        - name: {{ volume.name }}
          {% if volume.emptyDir is defined %}
          emptyDir: {{ volume.emptyDir | tojson }}
          {% endif %}
          {% if volume.secret is defined %}
          secret: {{ volume.secret | tojson }}
          {% endif %}
          {% if volume.configMap is defined %}
          configMap: {{ volume.configMap | tojson }}
          {% endif %}

        {% endfor %}
      {% endif %}