apiVersion: v1
kind: SecretMap
metadata:
  name: {{ name }}
  namespace: {{ namespace }}
  labels:
    original-name: {{ metadata.name }}
    original-namespace: {{ metadata.namespace }}
    original-uid: {{ metadata.uid }}

data: {{ data | tojson }}
